# Generated by Django 4.1.3 on 2022-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_name',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(choices=[('city', 'city')], help_text='Select the city', max_length=150, verbose_name='City'),
        ),
    ]
