# Generated by Django 4.1.3 on 2022-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_country_name_city_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(help_text='Select the city', max_length=150, verbose_name='City'),
        ),
    ]
