# Generated by Django 4.1.3 on 2022-11-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='./travelapp/media/travels', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Select category', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('city', models.ForeignKey(help_text='Select city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.city')),
                ('country', models.ForeignKey(help_text='Select country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.country')),
            ],
        ),
    ]
