# Generated by Django 4.1.3 on 2022-11-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tickets',
            field=models.IntegerField(default=10),
        ),
    ]
