# Generated by Django 4.1.3 on 2022-12-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_reviewandrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.DateTimeField(choices=[('date', 'date')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.purchase')),
            ],
        ),
    ]
