# Generated by Django 4.1.3 on 2022-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_variationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationdate',
            name='date_value',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='variationdate',
            name='time_value',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='variationdate',
            name='variation',
            field=models.CharField(choices=[('date', 'date'), ('time', 'time')], max_length=100),
        ),
    ]
