# Generated by Django 4.1.3 on 2022-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_variationdate_date_value_variationdate_time_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationdate',
            name='variation',
            field=models.CharField(choices=[('datetime', 'datetime')], max_length=100),
        ),
    ]
