# Generated by Django 4.1.3 on 2022-12-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_variationdate_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationdate',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='variationdate',
            name='time_value',
        ),
        migrations.AddField(
            model_name='variationdate',
            name='datetime_value',
            field=models.DateTimeField(null=True),
        ),
    ]
