# Generated by Django 4.1.3 on 2022-12-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_remove_variationdate_date_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(choices=[('datetime', 'datetime')], max_length=100)),
                ('variation_value', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.purchase')),
            ],
        ),
        migrations.DeleteModel(
            name='VariationDate',
        ),
    ]
