# Generated by Django 4.1.3 on 2022-12-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_variation_delete_variationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='tickets',
            new_name='persons',
        ),
    ]
